FROM ubuntu:20.04 as apt-items

ENV DEBIAN_FRONTEND="noninteractive" TZ="America"

RUN apt-get update && apt-get install -y \
    curl \
    git \
    gnupg \
    zip \
    unzip \
    jq \
    zlib1g-dev \
    sudo \
    groff

FROM apt-items as awsv2
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip" && \
  unzip awscliv2.zip && \
  sudo ./aws/install && \
  sudo rm awscliv2.zip

FROM awsv2 as tf-setup
RUN curl -O https://releases.hashicorp.com/terraform/1.3.0/terraform_1.3.0_linux_arm64.zip && \
    unzip terraform_1.3.0_linux_arm64.zip && \
    mv terraform /usr/local/bin/ && \
    rm -f terraform_1.3.0_linux_arm64.zip && \
    mkdir -p /terraform
